# Generated by Django 5.1.6 on 2025-04-09 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
